# Copyright 2025
# Iterative refinement agent loop for MedSAM-Agent
# Supports add_bbox, add_point and stop_action

import asyncio
import json
import logging
import os
from typing import Any

import numpy as np
from PIL import Image

from verl.experimental.agent_loop import ToolAgentLoop
from verl.experimental.agent_loop.tool_agent_loop import AgentData, AgentState
from verl.experimental.agent_loop.agent_loop import AgentLoopOutput, register
from verl.tools.schemas import ToolResponse
from qwen_vl_utils import process_vision_info

logger = logging.getLogger(__name__)
logger.setLevel(os.getenv("VERL_LOGGING_LEVEL", "INFO"))


@register("medsam_iterative_agent")
class MedSAMIterativeAgentLoop(ToolAgentLoop):
    """Agent loop for iterative segmentation refinement.
    
    This agent loop manages multi-turn interaction where the VLM can:
    1. add_bbox(bbox_2d) - add bounding box to initialize mask (first turn)
    2. add_point(point_2d, point_type) - add positive/negative points to refine mask
    3. stop_action() - terminate when satisfied
    
    The loop automatically detects stop_action and terminates the episode.
    
    Key feature: Maintains a persistent tool instance across multiple turns
    to enable the segmentation session to accumulate refinement history.
    """
    
    def __init__(self, *args, **kwargs):
        """Initialize with persistent instance tracking."""
        super().__init__(*args, **kwargs)
        # Track persistent instances for each tool (shared across all turns)
        self._persistent_instances = {}
        # Unique episode ID to avoid session conflicts across workers
        import uuid
        self._episode_id = str(uuid.uuid4())[:8]  # Short unique ID per episode
        # Track the latest mask generated by tools (before overlay conversion)
        self._latest_mask = None
        # Store reference to the original image for overlay creation
        self._original_image = None
        # Store all masks from each turn for IoU tracking
        self._mask_history = []  # List of PIL.Image masks, one per turn
    
    @classmethod
    def init_class(cls, config, tokenizer, processor, **kwargs):
        """Initialize class-level resources."""
        # Call parent initialization
        super().init_class(config, tokenizer, processor, **kwargs)
    
    def _create_overlay(self, original_image: Image.Image, mask: Image.Image) -> Image.Image:
        """Create an overlay image with semi-transparent green mask.
        
        Args:
            original_image: The original CT image (grayscale or RGB)
            mask: The segmentation mask (grayscale, 0-255)
        
        Returns:
            RGB image with semi-transparent green overlay
        """
        # Convert to RGB if needed
        if original_image.mode != 'RGB':
            original_rgb = original_image.convert('RGB')
        else:
            original_rgb = original_image.copy()
        
        original_np = np.array(original_rgb)
        
        # Resize mask to match original_image size if needed
        if mask.size != original_image.size:
            mask = mask.resize(original_image.size, Image.BILINEAR)
        
        # Convert mask to binary
        if mask.mode != 'L':
            mask = mask.convert('L')
        mask_np = np.array(mask)
        mask_binary = (mask_np > 127).astype(np.uint8)
        
        # Create overlay with semi-transparent green
        overlay = original_np.copy()
        green = np.array([0, 255, 0], dtype=np.uint8)
        alpha = 0.5
        
        # Blend: result = original * (1-alpha) + green * alpha where mask=1
        mask_3d = mask_binary[:, :, np.newaxis]  # (H, W, 1)
        overlay = (
            original_np * (1 - alpha * mask_3d) + 
            green * alpha * mask_3d
        ).astype(np.uint8)
        
        return Image.fromarray(overlay)
    
    async def _execute_single_tool_call(
        self,
        tool_call,
        tools_kwargs: dict[str, Any],
    ) -> tuple:
        """Execute a single tool call with persistent instance management.
        
        Override parent method to maintain tool instances across multiple turns.
        This allows the segmentation session to accumulate refinement history.
        """
        
        tool, instance_id = None, None
        tool_name = None
        tool_args = None
        success = False
        error_msg = None
        tool_execution_response = None
        tool_reward = 0.0
        res = {}
        
        try:
            tool_name = tool_call.name
            
            # Parse tool arguments
            try:
                tool_args = json.loads(tool_call.arguments)
            except json.JSONDecodeError as json_err:
                error_msg = f"Invalid JSON in tool arguments: {json_err.msg} at position {json_err.pos}"
                logger.error(f"JSON decode error for tool {tool_name}: {error_msg}")
                raise ValueError(error_msg) from json_err
            
            # Check if tool exists
            if tool_name not in self.tools:
                error_msg = f"Tool '{tool_name}' not found. Available tools: {list(self.tools.keys())}"
                logger.error(error_msg)
                raise KeyError(error_msg)
            
            tool = self.tools[tool_name]
            kwargs = tools_kwargs.get(tool_name, {})
            
            # Use persistent instance if already created, otherwise create new one
            if tool_name in self._persistent_instances:
                instance_id = self._persistent_instances[tool_name]
                logger.debug(f"[Episode {self._episode_id}] Reusing persistent instance for {tool_name}: {instance_id}")
            else:
                # Generate unique instance_id with episode prefix to avoid conflicts
                unique_instance_id = f"{self._episode_id}_{tool_name}"
                
                # Pass the unique instance_id to tool.create()
                create_kwargs = kwargs.get("create_kwargs", {})
                instance_id, _ = await tool.create(instance_id=unique_instance_id, create_kwargs=create_kwargs)
                
                self._persistent_instances[tool_name] = instance_id
                logger.debug(f"[Episode {self._episode_id}] Created new persistent instance for {tool_name}: {instance_id}")
            
            # Execute tool with persistent instance
            tool_execution_response, tool_reward, res = await tool.execute(instance_id, tool_args)
            success = True
            
        except json.JSONDecodeError as e:
            error_msg = f"Invalid JSON format in tool arguments: {str(e)}"
            logger.warning(f"JSON error when calling tool {tool_name}: {e}")
        except KeyError as e:
            error_msg = f"Tool not found or missing required field: {str(e)}"
            logger.warning(f"Key error when calling tool {tool_name}: {e}")
        except Exception as e:
            error_msg = str(e)
            logger.warning(f"Error when executing tool {tool_name}: {e}")
        
        # NOTE: We do NOT call tool.release() here anymore!
        # Instances will be released when the episode ends
        
        # Handle errors
        if not success:
            return (
                ToolResponse(text=f"Error when executing tool: {error_msg}"),
                0.0,
                {},
            )

        # Process successful tool execution response
        tool_response_text = tool_execution_response.text
        if tool_response_text and len(tool_response_text) > self.max_tool_response_length:
            if self.tool_response_truncate_side == "left":
                tool_response_text = tool_response_text[: self.max_tool_response_length] + "...(truncated)"
            elif self.tool_response_truncate_side == "right":
                tool_response_text = "(truncated)..." + tool_response_text[-self.max_tool_response_length :]
            else:
                length = self.max_tool_response_length // 2
                tool_response_text = tool_response_text[:length] + "...(truncated)..." + tool_response_text[-length:]

        # Create ToolResponse
        tool_response_kwargs = {"text": tool_response_text}
        for attr_name in ["image", "video"]:
            if hasattr(tool_execution_response, attr_name):
                attr_value = getattr(tool_execution_response, attr_name)
                if attr_value is not None:
                    tool_response_kwargs[attr_name] = attr_value

        return ToolResponse(**tool_response_kwargs), tool_reward, res
    
    async def run(self, sampling_params: dict[str, Any], **kwargs) -> AgentLoopOutput:
        """Run the iterative refinement loop.
        
        Flow:
        1. Dataset constructs the initial messages with system prompt
        2. Agent loop runs the state machine (PENDING → GENERATING → PROCESSING_TOOLS → ...)
        3. Continue until stop_action is called or max turns reached
        
        Note: The system prompt and first turn prompt should be set by the Dataset,
        not by this method, to avoid conflicts with raw_prompt.
        """
        # Reset persistent instances at the start of each episode
        self._persistent_instances = {}
        self._latest_mask = None  # Reset latest mask tracking
        self._mask_history = []  # Reset mask history
        
        # Save the original image before calling super().run()
        # This is needed as a fallback if no mask is generated
        original_image_data = kwargs.get("multi_modal_data", {}).get("image", None)
        if isinstance(original_image_data, list) and len(original_image_data) > 0:
            self._original_image = original_image_data[0]
        elif original_image_data is not None:
            self._original_image = original_image_data
        else:
            raise ValueError("Original image data is required to run the MedSAM iterative agent loop.")
        
        try:
            # Call parent ToolAgentLoop.run which implements the state machine
            # The parent will use the messages from kwargs["raw_prompt"] as-is
            output = await super().run(sampling_params, **kwargs)
            
            # Check if stop_action was called by looking at tool calls
            stopped = self._check_if_stopped(output)
            
            # Store termination status
            output.extra_fields["stopped"] = stopped
            
            # Reuse pred_mask key to store all masks from each turn (list of PIL Images)
            # For backward compatibility: single mask → single item, multiple masks → list
            if len(self._mask_history) > 0:
                # Multi-turn or single-turn with mask history
                # IMPORTANT: Create a copy of the list to avoid being cleared by cleanup
                mask_list_copy = list(self._mask_history)
                output.extra_fields["pred_mask"] = mask_list_copy
                logger.debug(f"[MASK ASSIGNMENT] Assigned mask_history COPY as list with {len(mask_list_copy)} masks")
                logger.debug(f"[MASK ASSIGNMENT] Original list id: {id(self._mask_history)}, Copy list id: {id(mask_list_copy)}")
                logger.debug(f"[MASK ASSIGNMENT] Assigned pred_mask type: {type(output.extra_fields['pred_mask'])}, is list: {isinstance(output.extra_fields['pred_mask'], list)}")
            elif self._latest_mask is not None:
                # Fallback: single mask without history (backward compatibility)
                output.extra_fields["pred_mask"] = self._latest_mask
                logger.debug(f"[MASK ASSIGNMENT] Assigned single latest_mask (fallback), type: {type(self._latest_mask).__name__}")
            else:
                # No mask was generated - create all-zero mask as final fallback
                original_image = self._original_image
                    
                if original_image is not None:
                    # Create all-zero mask (black image) with same size as original
                    if isinstance(original_image, Image.Image):
                        width, height = original_image.size
                    elif isinstance(original_image, np.ndarray):
                        height, width = original_image.shape[:2]
                    else:
                        raise ValueError("Cannot determine original image size for fallback mask")
                    # Create all-zero mask as PIL Image (grayscale)
                    fallback_mask = Image.new('L', (width, height), 0)
                    output.extra_fields["pred_mask"] = fallback_mask
                else:
                    raise ValueError("Cannot create fallback mask - original image data is missing")
            
            return output
            
        finally:
            # Clean up persistent instances and free GPU memory when episode ends
            logger.debug(f"[CLEANUP] Starting cleanup - _mask_history length before clear: {len(self._mask_history)}, id: {id(self._mask_history)}")
            await self._cleanup_episode_resources()
            logger.debug(f"[CLEANUP] After cleanup - _mask_history length: {len(self._mask_history)}, id: {id(self._mask_history)}")
    
    async def _cleanup_episode_resources(self):
        """Clean up all resources at the end of an episode to prevent memory leaks."""
        import torch
        import gc
        
        # 1. Release all persistent tool instances
        for tool_name, instance_id in list(self._persistent_instances.items()):
            try:
                if instance_id and tool_name in self.tools:
                    tool = self.tools[tool_name]
                    await tool.release(instance_id)
                    logger.debug(f"[Cleanup] Released persistent instance for {tool_name}: {instance_id}")
            except Exception as e:
                logger.warning(f"[Cleanup] Failed to release instance {instance_id} for {tool_name}: {e}")
        
        self._persistent_instances.clear()
        
        # 2. Clear image references to free memory
        self._latest_mask = None
        self._original_image = None
        self._mask_history = []
        
        # 3. Force GPU memory cleanup if CUDA is available
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
            torch.cuda.synchronize()
        
        # 4. Force Python garbage collection
        gc.collect()
        
        logger.debug(f"[Cleanup] Completed resource cleanup for episode {self._episode_id}")
    
    def _check_if_stopped(self, output: AgentLoopOutput) -> bool:
        """Check if stop_action was called during the episode."""
        # This is a simple heuristic - you can improve it by tracking tool call history
        # For now, we check if the response contains stop_action in the text
        if output.response_ids:
            response_text = self.tokenizer.decode(output.response_ids, skip_special_tokens=True)
            if "stop_action" in response_text:
                return True
        return False


    async def _handle_pending_state(self, agent_data: AgentData, sampling_params: dict[str, Any]) -> AgentState:
        """Handle the pending state: prepare the prompt and start generation.
        
        This is called for the first turn. We need to extract images from messages
        using process_vision_info to maintain consistency with multi-turn processing.
        """
        if self.processor is not None:
            raw_prompt = await self.loop.run_in_executor(
                None,
                lambda: self.processor.apply_chat_template(
                    agent_data.messages,
                    # tools=self.tool_schemas,
                    add_generation_prompt=True,
                    tokenize=False,
                    **self.apply_chat_template_kwargs,
                ),
            )
            
            # Extract images from messages using qwen_vl_utils (consistent with multi-turn handling)
            # This ensures that images embedded in the structured messages are properly extracted
            if "Qwen3VLProcessor" in self.processor.__class__.__name__:
                image_inputs, video_inputs = process_vision_info(agent_data.messages, image_patch_size=16)
            else:
                image_inputs, video_inputs = process_vision_info(agent_data.messages)
             
            # Use do_resize=False to avoid duplicate resizing since process_vision_info already handled it
            model_inputs = self.processor(
                text=[raw_prompt], 
                images=image_inputs, 
                videos=video_inputs,
                do_resize=False,
                padding=True,
                return_tensors="pt"
            )
            # Update agent_data.image_data for consistency (will be used by parent class)
            agent_data.image_data = image_inputs if image_inputs else None
            agent_data.prompt_ids = model_inputs.pop("input_ids").squeeze(0).tolist()
        else:
            agent_data.prompt_ids = await self.loop.run_in_executor(
                None,
                lambda: self.tokenizer.apply_chat_template(
                    agent_data.messages,
                    # tools=self.tool_schemas,
                    add_generation_prompt=True,
                    tokenize=True,
                    **self.apply_chat_template_kwargs,
                ),
            )
        return AgentState.GENERATING
    
    async def _handle_generating_state(
        self, agent_data: AgentData, sampling_params: dict[str, Any], ignore_termination: bool = False
    ) -> AgentState:
        """Override parent to enforce tool call requirement for MedSAM refinement.
        
        Key behavior: If the model generates a response WITHOUT tool calls, 
        terminate immediately instead of continuing.
        """   
        # Call parent's generating state handler
        next_state = await super()._handle_generating_state(agent_data, sampling_params, ignore_termination)
                
                # After parent processing, check if we should have tool calls but don't
        if next_state == AgentState.PROCESSING_TOOLS:
            # Validate that all tool calls are allowed tools
            allowed_tools = {"add_bbox", "add_point", "stop_action"}
            invalid_tools = []
            
            for tool_call in agent_data.tool_calls:
                if tool_call.name not in allowed_tools:
                    invalid_tools.append(tool_call.name)
            
            if invalid_tools:
                logger.warning(
                    f"[MedSAM Agent] Model called invalid tool(s) in turn {agent_data.assistant_turns}: {invalid_tools}. "
                    f"Only allowed tools are: {allowed_tools}. Terminating episode."
                )
                return AgentState.TERMINATED
            
            # Normal path: tool calls detected and all are valid
            return next_state
        elif next_state == AgentState.TERMINATED:
            # Already terminated by parent logic (max turns, length, etc.)
            return next_state
        elif next_state == AgentState.INTERACTING:
            # In MedSAM context, we should never reach INTERACTING state
            # because we always expect tool calls (add_bbox, add_point or stop_action)
            logger.warning(
                f"[MedSAM Agent] Model did not call any tool in turn {agent_data.assistant_turns}. "
                "This violates the refinement protocol. Terminating episode."
            )
            return AgentState.TERMINATED
        else:
            # Parent returned TERMINATED (no tool calls and no interaction config)
            # This is also a failure case for MedSAM - model should always call tools
            logger.warning(
                f"[MedSAM Agent] Model generated response without tool calls in turn {agent_data.assistant_turns}. "
                "Expected one of: add_bbox, add_point, stop_action. Terminating."
            )
            return AgentState.TERMINATED
    
    async def _handle_processing_tools_state(self, agent_data: AgentData) -> AgentState:
        """Override to handle tool execution and present results as user messages with overlay images.
        
        This method:
        1. Executes tool calls to get updated masks
        2. Creates overlay images (original + mask)
        3. Presents the overlay to the model as a USER message (not tool message)
        4. Maintains the original mask for reward computation
        """
        import asyncio
        from verl.utils.profiler import simple_timer
        
        # Check if stop_action is in the tool calls
        for tool_call in agent_data.tool_calls:
            if tool_call.name == "stop_action":
                # For stop_action, we still need to execute it to get the final mask
                # but we'll terminate immediately after
                break
        
        # Execute tool calls (similar to parent class, but we won't add tool messages)
        tasks = []
        tool_call_names = []
        for tool_call in agent_data.tool_calls[: self.max_parallel_calls]:
            tasks.append(self._execute_single_tool_call(tool_call, agent_data.tools_kwargs))
            tool_call_names.append(tool_call.name)
        
        with simple_timer("tool_calls", agent_data.metrics):
            responses = await asyncio.gather(*tasks)
        # Process tool responses - collect new masks
        new_mask = None
        for tool_response, tool_reward, _ in responses:
            # Collect tool rewards
            if tool_reward is not None:
                agent_data.tool_rewards.append(tool_reward)
            
            # Extract new mask from tool response
            if tool_response.image:
                if isinstance(tool_response.image, list):
                    new_mask = tool_response.image[0] if len(tool_response.image) > 0 else None
                else:
                    new_mask = tool_response.image
                logger.debug(f"Got new mask from tool: type={type(new_mask)}")
        
        # Check if this was a stop_action
        is_stop_action = any(tc.name == "stop_action" for tc in agent_data.tool_calls)
        
        if is_stop_action:
            # For stop_action, save the final mask but DON'T add to history
            # (stop_action returns the existing mask, not a new one)
            if new_mask is not None:
                self._latest_mask = new_mask
                # DO NOT append to _mask_history to avoid duplicate
                logger.debug(f"Stored final mask from stop_action (total masks in history: {len(self._mask_history)})")
            return AgentState.TERMINATED
        
        # For normal tool calls, create overlay and present as user message
        if new_mask is None:
            logger.warning("No mask returned from tool, cannot create overlay")
            return AgentState.TERMINATED
        
        # Store the original mask before overlay conversion and add to history
        self._latest_mask = new_mask
        self._mask_history.append(new_mask)  # Add to mask history for per-turn IoU tracking
        logger.debug(f"Added mask to history (turn {agent_data.assistant_turns}, total masks: {len(self._mask_history)})")

        # Get original image - use the saved reference from initialization
        # This ensures we always use the original CT image for overlay, not a previous overlay
        original_image = self._original_image
        if original_image is None:
            logger.error("Cannot create overlay: original image is None")
            return AgentState.TERMINATED
        
        # Create overlay
        try:
            overlay_image = self._create_overlay(original_image, new_mask)
        except Exception as e:
            logger.error(f"Failed to generate overlay: {e}", exc_info=True)
            return AgentState.TERMINATED
        
        # Construct user message with overlay image
        later_turn_prompt = (
            "Here is the updated mask after your previous action.\n"
            "Based on this, what is your next action? "
            "If the mask is now accurate, you can call 'stop_action' to finish."
        )
        
        # Add user message with structured content (image placeholder + text)
        # The image placeholder tells apply_chat_template where to insert image tokens
        # The actual image object is passed separately via image_data
        user_message = {
            "role": "user",
            "content": [
                {
                    "type": "image",
                    "image": overlay_image  # Placeholder text for image
                },
                {
                    "type": "text",
                    "text": later_turn_prompt
                }
            ]
        }
        agent_data.messages.append(user_message)
        
        if self.processor is not None:
            # Re-encode the complete conversation history
            # CRITICAL: Must include tools parameter to maintain consistency with first turn encoding
            # Without tools, some models (like Qwen2-VL) may skip the system prompt
            curr_raw = await self.loop.run_in_executor(
                None,
                lambda: self.processor.apply_chat_template(
                    agent_data.messages,  # Complete conversation: system + user1 + assistant1 + user2
                    # tools=self.tool_schemas,  # IMPORTANT: Include tools to preserve system prompt
                    add_generation_prompt=True,  # Add generation prompt for next assistant turn
                    tokenize=False,
                    **self.apply_chat_template_kwargs,
                ),
            )

            # Extract images and videos from messages using qwen_vl_utils
            # This extracts PIL Images from the structured messages and preprocesses them
            if "Qwen3VLProcessor" in self.processor.__class__.__name__:
                image_inputs, video_inputs = process_vision_info(agent_data.messages, image_patch_size=16)
            else:
                image_inputs, video_inputs = process_vision_info(agent_data.messages)

            # CRITICAL: Update agent_data.image_data with the preprocessed images
            # The parent class will pass this to vLLM's generate() method
            # image_inputs is what process_vision_info returns (preprocessed tensors or PIL Images)
            agent_data.image_data = image_inputs if image_inputs else None
            
            # Use do_resize=False to avoid duplicate resizing since process_vision_info already handled it
            curr_model_inputs = self.processor(
                text=[curr_raw],
                images=image_inputs,
                videos=video_inputs,
                do_resize=False,
                padding=True,
                return_tensors="pt",
            )

            new_prompt_ids = curr_model_inputs["input_ids"].squeeze(0).tolist()
        
            # Calculate how many new tokens were added
            old_prompt_length = len(agent_data.prompt_ids)
            new_tokens_count = len(new_prompt_ids) - old_prompt_length
            
            # Simplified approach: Since we now include tools parameter consistently,
            # the encoding is aligned correctly. We just need to extend the response_mask
            # for the new user message tokens (mask=0).
            
            # Replace prompt_ids with the new complete encoding
            agent_data.prompt_ids = new_prompt_ids
            
            # Extend response_mask with 0s for the new user message tokens
            agent_data.response_mask += [0] * new_tokens_count
            
            # Update logprobs if tracking
            if agent_data.response_logprobs:
                agent_data.response_logprobs += [0.0] * new_tokens_count
        else:
            # Fallback for tokenizer-only mode (no processor)
            response_ids = await self.loop.run_in_executor(
                None,
                lambda: self.tokenizer.apply_chat_template(
                    [user_message],
                    add_generation_prompt=True,
                    tokenize=True,
                    **self.apply_chat_template_kwargs
                ),
            )
            response_ids = response_ids[len(self.system_prompt):]
            agent_data.prompt_ids += response_ids
            agent_data.response_mask += [0] * len(response_ids)
            if agent_data.response_logprobs:
                agent_data.response_logprobs += [0.0] * len(response_ids)
        
        # Check if we would exceed response length
        if len(agent_data.response_mask) >= self.response_length:
            logger.warning("Would exceed response_length, terminating")
            return AgentState.TERMINATED
        
        # Increment user turn count
        agent_data.user_turns += 1

        # Return to GENERATING state for next turn
        return AgentState.GENERATING
